name: Build

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-2019
    steps:
      - name: main
        run: |
          Start-Process powershell -Verb runAs
          #dism /online /get-features
          #dism /online /get-capabilities
          dism /online /Add-Capability /CapabilityName:OpenSSH.Server~~~~0.0.1.0
          #Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
          #Get-WindowsCapability -Online
          #Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
