name: Build

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-2019
    steps:
      - name: main
        run: |
          choco install ngrok.portable
          Start-Process powershell -Verb runAs
          Invoke-WebRequest 'https://github.com/PowerShell/Win32-OpenSSH/releases/download/v8.1.0.0p1-Beta/OpenSSH-Win64.zip' -O OpenSSH-Win64.zip
          Expand-Archive -Path OpenSSH-Win64.zip -DestinationPath 'C:/Program Files'
          cd 'C:/Program Files/OpenSSH-Win64'
          powershell.exe -ExecutionPolicy Bypass -File install-sshd.ps1
          New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH SSH Server' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
          #Start-Service sshd
          ngrok http 49978
          tasklist
          netstat
          #dism /online /get-features
          #dism /online /get-capabilities
          #dism /online /Add-Capability /CapabilityName:OpenSSH.Client~~~~0.0.1.0
          #dism /online /Add-Capability /CapabilityName:OpenSSH.Server~~~~0.0.1.0
          #Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
          #Get-WindowsCapability -Online
          #Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
