name: Build

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-2019
    steps:
      - name: main
        run: |
          Start-Process powershell -Verb runAs
          New-NetFirewallRule -Name sshd -DisplayName 'OpenSSH SSH Server' -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22
          #dism /online /get-features
          #dism /online /get-capabilities
          #dism /online /Add-Capability /CapabilityName:OpenSSH.Client~~~~0.0.1.0
          #dism /online /Add-Capability /CapabilityName:OpenSSH.Server~~~~0.0.1.0
          #Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
          #Get-WindowsCapability -Online
          #Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
