name: Build

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-2019
    steps:
      - name: main
        run: |
          Start-Process powershell -Verb runAs
          dism /online /get-features
          Get-WindowsCapability -Online
          ls
          Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
          #Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
