name: Build

on: [push, pull_request]

jobs:
  Ubuntu:
    Windows:
      runs-on: windows-2019
      steps:
      - run: |
        Get-WindowsCapability -Online
        ls
        #Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
        #Get-WindowsCapability -Online | ? Name -like 'OpenSSH*'
